apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
    spec:
      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
          - containerPort: 3000
        volumeMounts:
          - mountPath: "/var/lib/grafana"
            name: grafana-pv

---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
  - name: grafana-http
    protocol: TCP
    port: 3000
    targetPort: 3000

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: grafana
  labels:
    app.kubernetes.io/name: grafana
spec:
  storageClassName: grafana-vol
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/alfred/kub-mnt"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  storageClassName: grafana-vol
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
